name: Build and Publish Native App

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4.2.1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
      - name: Build Native
        run: ./gradlew build -Dquarkus.native.enabled=true

      # Archive the build output
      - name: Archive build artifacts
        run: |
          mkdir -p release
          cp build/prismx-runner release/ # Replace with your actual build output path

      # Upload artifacts to the workflow for debugging or sharing
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Download the build artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: release/

      # Create or update a GitHub release
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/prismx-runner # Upload all files in the release directory
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

